### ISSUE TITLE
Reproduce the result from HuggingFace

### ISSUE THREAD

**Issue by SlimeVRX** [JiauZhang/Text2Video-Zero#1]
Hi,

Text2Video-Zero code open at [huggingface.co/spaces](https://huggingface.co/spaces/PAIR/Text2Video-Zero/tree/main)

It requires A100 GPU to run, Can you help me implement the code to run on Colab?

Thanks for your research!

Best regards,

Tin Nguyen Thanh

**Comment by JiauZhang** [comment]
I only use P100 run my current code on Kaggle, you can also try it.

**Comment by SlimeVRX** [comment]
Thanks, I ran your code on Colab Tesla T4 GPU, it works.

Looking forward to your work!

**Comment by JiauZhang** [comment]
I update version 2, you can try it too.

**Comment by SlimeVRX** [comment]
Thank! I will try it.

**Comment by lordmen99** [comment]
> Thanks, I ran your code on Colab Tesla T4 GPU, it works.
> 
> Looking forward to your work!

can u share demo please, wanna try it

**Comment by SlimeVRX** [comment]
Ok, Wait for me a few minutes

**Comment by SlimeVRX** [comment]
Hi,

I sent [Text2Video-Zero-Colab](https://colab.research.google.com/drive/1Ke-qGR2tIkbtpT_5aEx6D5_N7lX0TEaY?usp=sharing)

**Comment by lordmen99** [comment]
> huggingface.co/spaces

its nice, i will try it

**Comment by SlimeVRX** [comment]
Hi @JiauZhang

Updated Text2Video-Zero code with Pose and Canny, Please update!

![image](https://user-images.githubusercontent.com/99313947/227871622-b1367b0d-49d1-4f33-b903-9ee138deecdc.png)

**Comment by JiauZhang** [comment]
> Hi @JiauZhang
> 
> Updated Text2Video-Zero code with Pose and Canny, Please update!
> 
> ![image](https://user-images.githubusercontent.com/99313947/227871622-b1367b0d-49d1-4f33-b903-9ee138deecdc.png)

I will add these feature this week.

**Comment by SlimeVRX** [comment]
Thank for your work!

**Comment by SlimeVRX** [comment]
Update: GPU VRAM 12 GB [Supported](https://github.com/Picsart-AI-Research/Text2Video-Zero)

![image](https://user-images.githubusercontent.com/99313947/228399834-b616220f-9f4f-4f83-bc88-670a8c0de9f1.png)

**Comment by JiauZhang** [comment]
@SlimeVRX My GPU memory usage:
![gpu_usage](https://user-images.githubusercontent.com/38578095/228811170-f5307736-82bf-43ce-90e4-f53375f1ac59.png)

**Comment by SlimeVRX** [comment]
Hi,

Sorry, I mean original Text2Video-Zero on HuggingFace requires A100, can't run on Colab
They tried to limit GPU to 12GB

**Comment by JiauZhang** [comment]
Got it.
The model is the same. Theoretically, only batch size and some intermediate variables can cause different memory usage

**Comment by SlimeVRX** [comment]
Hi, Thank you for the explanation!
