### ISSUE TITLE
Version 1   2 3     How to switch between different versions?

### ISSUE THREAD

**Issue by zhanghongyong123456** [JiauZhang/Text2Video-Zero#3]
1.  How to switch between different versions（1，2，3，）
2.
I wonder what should I do to generate a longer video,
similar to  text-to-video-ms-1.7b    25s  video

**Comment by JiauZhang** [comment]
1. you could checkout different commit id according to the version you want
2. I think the result of using Text2Video-Zero for StableDiffusion is more like doing image editing. If you want to produce long-term videos, I feel that using Text2Video-Zero's method on ControlNet or T2I-Adapter would be better.
