### ISSUE TITLE
ControlNet Question

### ISSUE THREAD

**Issue by ltejedor** [JiauZhang/Text2Video-Zero#5]
Hello! Thank you for this implementation, much easier to read through and learn from.

Have you actually gotten the Text2Video running with ControlNet? What does that code look like?

Thank you!

**Comment by JiauZhang** [comment]
I implement this project when the official author dosen't open source the code, but now official implementation(https://github.com/Picsart-AI-Research/Text2Video-Zero) is available, so I delay this project.

If you want to implement it based on controlnet, you should rewrite the __call__ function(https://github.com/JiauZhang/Text2Video-Zero/blob/main/zero.py#L29), you could reference current code based on stable diffusion, I think it should not be difficult to implement.

Hoping This Helps.
