### ISSUE TITLE
Running the code offline

### ISSUE THREAD

**Issue by ghost** [JiauZhang/Text2Video-Zero#6]
Greetings,

I tried running this code offline, but the code failed. The code successfully runs when connected to internet. How do I run the code offline?

**Comment by ghost** [comment]
Looking forward to hearing from you at the earliest.

**Comment by JiauZhang** [comment]
This code donwload model weights from huggingface online, so if you want run offline, you need to check how to use offline weights with hugggingface. https://github.com/huggingface

**Comment by ghost** [comment]
Greetings,

Thank you for your response. I will check the GitHub link.
